apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-password
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  password: {{ .Values.password  | b64enc | quote }}

---

{{- $schema := .Values.sparkEventLogStorage.cloudProvider }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-sparkEventLogStorage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if eq $schema "amazon" }}
  AWS_ACCESS_KEY_ID: {{ .Values.sparkEventLogStorage.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.sparkEventLogStorage.awsSecretAccessKey | b64enc | quote }}
  {{- else if eq $schema "azure" }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ .Values.sparkEventLogStorage.azureStorageAccountName | b64enc | quote }}
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.sparkEventLogStorage.azureStorageAccessKey | b64enc | quote }}
  {{- else if eq $schema "google" }}
  google.json: {{ .Values.sparkEventLogStorage.googleJson | quote }}
  {{- end }}
