# Default values for zeppelin
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: banzaicloud/zeppelin-server
  tag: v0.9.0-k8s-1.0.56
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2
    memory: 2048
  requests:
    cpu: 500m
    memory: 1024

additionalOptions:

service:
  type: ClusterIP
  internalPort: 8080
  externalPort:  8080
  rpcPort: 38853

username: "admin"
password: "zeppelin"

logService:
  zeppelinLogLevel: DEBUG
  zeppelinFacility: LOCAL4
  zeppelinLogPattern: "%5p [%d] ({%t} %F[%M]:%L) - %m%n"
  sparkLogLevel: INFO
  sparkFacility: LOCAL4
  sparkLogPattern: "[%p] XXX %c:%L - %m%n"
  applicationLoggerName: application
  applicationLogLevel: INFO
  applicationFacility: LOCAL4
  applicationLogPattern: "[%p] XXX %c:%L - %m%n"

ingress:
  enabled: false

ingresspasswordgenerator:
  image:
    repository: banzaicloud/htpasswd-gen
    tag: "0.1"
    pullPolicy: IfNotPresent

pipelineIngress:
  enabled: true
  ingressURL:
  baseURL: /zeppelin
  auth:
    enabled: false
    username: ""
    password: ""

notebookStorage:
  type: ""
  path: ""
azureStorageAccountName: ""
azureStorageAccessKey: ""

sparkSubmitOptions:
  k8sNameSpace: default
  sparkDriverCores: 1
  sparkDriverLimitCores: 2
  sparkExecutorCores: 1
  sparkDriverMemory: 4G
  sparkExecutorMemory: 2G
  sparkMetricsConf: /opt/spark/conf/metrics.properties
  dynamicAllocation: false
  shuffleService: false
  sparkImage: banzaicloud/zeppelin-server:v0.9.0-k8s-1.0.56
  sparkLocalDir: /tmp/spark-local
  eventLogDirectory: ""
  driverServiceAccountName: "spark"

sparkEventLogStorage:
  cloudProvider: ""
  logDirectory: ""

  awsAccessKeyId: ""
  awsSecretAccessKey: ""

  azureStorageAccessKey: ""
  azureStorageAccountName: ""

  googleJson: ""

  secretName: ""
